### ISSUE TITLE
Unsure about ExtendedFirmwareFeaturesMask

### ISSUE THREAD

**Issue by alessaba** [5T33Z0/Clover-Crate#1]
Hi,
I am trying to update Monterey beta 6 to Monterey 12.0.1

First of all setting the j160 HWTarget make the installer app say the device is unsupported, removing does the trick though

I also read that to continue the update, ExtendedFirmwareFeatures and its mask need to be set

i seem to have understood [how to calculate](https://github.com/acidanthera/OpenCorePkg/blob/master/Include/Apple/IndustryStandard/AppleFeatures.h) the first variable, but i don't know how to calculate the mask. Using the values from Clover's sample config plist does not work, as the system reboots indefinitely after monterey detects something is not right

Any help is appreciated.

**Comment by 5T33Z0** [comment]
I don't know, sorry. Slice never explained it. He just added it and mentioned it in the clover changes thread on insanelymac and that's about it. Installtion is working fine with OpenCore.

It's also not implementd in the official release build. You need to download the last build from here: https://github.com/CloverHackyColor/CloverBootloader/actions (look inside the entries and download from there).

**Comment by alessaba** [comment]
Well yeah, but this should be a Clover Repo, i'd like to keep using Clover if possible 

It's a bit sad, seems like supporting Clover and using it in 2021 only gets "use OpenCore" replies, even from people very close to the Clover project. Seems like nobody really cares anymore about Clover :-/

**Comment by alessaba** [comment]
Please keep this issue open, maybe someone has found a way to calculate it.

**Comment by 5T33Z0** [comment]
Well, this is not a Clover Repo, this is a documentation repo, due to the fact, that documentation for clvoer in general is bad – as you might have noticed.

**Comment by 5T33Z0** [comment]
Explanation:

"Rev 5140: Implemented ExtendedFirmwareFeatures. 
  
Old FirmwareFeatures are 32bit only. It seems not enough for new Macs and new macOS. Since Monterey beta8 we need the bit 35 to be set. So we can replace old settings FirmwareFeatures in config.plist->SMBIOS with new ExtendedFirmwareFeatures which can be up to 64 bits.
  
Even I have model iMac17,1 I can't update Monterey until I set ExtendedFirmwareFeatures with this bit set. 
  
If we have ExtendedFirmwareFeatures then we need no old FirmwareFeatures. 
  
Backward compatibility: old config.plist will work with old systems."

**Source**: https://www.insanelymac.com/forum/topic/304530-clover-change-explanations/?do=findComment&comment=2768896

If you have a look in the fields in Clover Configuratore (update it!) you can see that there's nothing more  than a bunch of zeros added in front to turn it into 64 bit:

![Bildschirmfoto](https://user-images.githubusercontent.com/76865553/139641423-d014bf7b-559d-4069-85d8-7cdb6d1c49a5.png)

**Comment by alessaba** [comment]
That mask Doesn't even include Bit 35... it should not even boot a Monterey installer, in theory, which was the entire reason of this issue. 

Whatever, i'll try to find a more detailed guide somewhere, or just switch to OpenCore

**Comment by 5T33Z0** [comment]
First of all: I don't like your tone. I didn't have to look into this, yet I still did.
2nd of all: THIS is an example, generated by Clover Configurator. 
3rd:  This example is for a MacBookPro10,1 which uses a 32 bit mask since it's a legacy product. Which of course doesn't boot macOS Monterey installer (it does it in OpenCore with a new set of patches I utilized).

So if you want to complain about the mask or how it works, aim your critizism toward the developers of clover and Clover configurator , not me!

**Comment by alessaba** [comment]
Yeah, you are right, at least you researched something. Some times the Clover Devs just said "it works on my end" and stopped helping, so thank you for that at least.

I am just frustrated with the Hackintosh community in general, because Clover gets little support, most people tell you to switch to OpenCore, and then there is confusing info on that, too. 

I had OpenCore working pretty well last year, but iGPU support was easier for me to do in Clover. Then after some updates everything in my opencore config broke and i basically would have to redo everything to use it... I hoped that by using Clover, i could just overcome the Monterey installer issue and be fine

You are right, it's not even your fault, just the toxic community in general, and i replied in a somewhat toxic way too :-(

**Comment by 5T33Z0** [comment]
I understand your frustration – that is why I created this repo in the first place.

Bottom Line is: the most talented devs work on OpenCore. New discoveries are made there first. Then the get hammered into clover somehow and will be documented as badly as it is.

So my suggesrion is: for current Hardware and macOS: use OpenCore.
